export const getMockState={
      withNoNotes:()=>({
          byId:{},
          ids:[],
          openNoteId:null
      }),
      withOneNote:()=>({
          byId:{
              "id-123":{
                  id:"id-123",
                  content:"Hi",
                  timeStamp:1
              }
          },
          ids:["id-123"],
          openNoteId:"id-123"
      }),
      withNoOpenNotes:()=>({
          byId:{
          "id-123":{
              id:"id-123",
              content:"Hi",
              timeStamp:1
          }
          },
          ids:["id-123"],
          openNoteId: null
      })
}